### ISSUE TITLE
ArtKit pagination inventory.

### ISSUE THREAD

**Issue by mibby** [wispoffates/ArtMap#1]
Would it be possible to update the ArtKit with pagination including all new dye types and tools? Currently if forceArtKit: true is set, players are not able to make use of the new dye types. A possible solution to this is implementing an inventory pagination so players can cycle between inventories in their inventory while keeping their hotbar persistent to hold onto tools and dyes wanted while cycling.

Inventory example.

```
- - - - - - - - -
- - - - - - - - -
- - - - - - - - -

- - - - - - - - -
```

First page.
```
X X X X X X X X X
X X X X X X X X X
X X X X X X X X >

B C F - - - - - I
```

Center page.
```
X X X X X X X X X
X X X X X X X X X
< X X X X X X X >

B C F - - - - - I
```

Last page.
```
X X X X X X X X X
X X X X X X X X X
< X X X X X X X X

B C F - - - - - I
```

Context
```B = Bucket ``` ``` C = Coal ``` ``` F = Feather ``` ``` I = Paint Brush ```
```X = Dye ``` ```- = Empty Space```
```> = Forward Page ``` ``` < = Back Page```

Hotbar would ideally be persistent and not change when cycling inventory so players can keep all important tools on their main bar for use and drag dyes they want to keep across cycling. Which would also allow them to dye the bucket with all 51 types and keep it persistent without it erasing when cycling.

**Comment by wispoffates** [comment]
Been working on infrastructure stuff also moved over to Gitlab.  https://gitlab.com/BlockStack/ArtMap .
Your issues migrated over but are now owned by me.  Once I hear from you I'm going to close down issues here to finish moving over there.  I hopefully will get back to these issues in the next couple of days.

**Comment by mibby** [comment]
Sure, no problem. I'll create a gitlab account and report future issues over there. You are more than welcome to close tickets here and take ownership of them elsewhere.
